foreground = yes
debug = info
output = /hw2/logs/stunnel.log
pid = /hw2/logs/stunnel.pid

[mtls-http]
accept = 0.0.0.0:4433
connect = 127.0.0.1:8000
cert = /hw2/certs/server.crt
key = /hw2/certs/server.key
CAfile = /hw2/certs/ca.crt
verify = 2
